
sudo: false
language: cpp
compiler:
  - gcc
  - clang
env:
  - CE_BUILD_TYPE=Debug
  - CE_BUILD_TYPE=Release
addons:
   apt:
      sources:
         - ubuntu-toolchain-r-test
      packages:
         - g++-5
         - cmake
         - libev-dev
         - libpqxx3-dev
before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
before_script:
  - mkdir build
  - cd build
  - cmake ../ -DBUILD_MODULES=OFF
script:
  - make
notifications:
  irc:
    channels:
      - "irc.bad-alloc.net#bad_alloc"
    template:
      - "%{repository_slug} (%{branch} @ %{commit}) : %{message} %{result} "
