
sudo: false
language: cpp
compiler:
  - gcc
  - clang
addons:
   apt:
      sources:
         - kalakris-cmake
      packages:
         - cmake
before_script:
  - mkdir build
  - cd build
  - cmake ../
script:
  - make
