
sudo: false
language: cpp
compiler:
  - gcc
  - clang
addons:
   apt:
      packages:
         - cmake
         - libev-dev
         - libpqxx-dev
before_script:
  - mkdir build
  - cd build
  - cmake ../
script:
  - make
